name: Test Python app
run-name: ${{github.actor}} has triggered the pipeline

on:
  push:
    branches: -master
  workflow_dispatch:

jobs:
  python-app:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: "pip"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Run tests
        run: |
          python -m unittest discover tests/
      - name: Build package
        run: |
          python setup.py sdist bdist_wheel
      - name: Publish package
        uses: actions/upload-artifact@v4
