name: Test Python app
run-name: ${{github.actor}} has triggered the pipeline

on:
  push:
    branches: -master
  workflow_dispatch:

jobs:
  python-app:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
      - run: python my_script.py
